AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'apim-landingzone'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/xuhongl'
CICD_AGENT_TYPE: none
CERT_TYPE: 'selfsigned'
